mysite/blog/urls.py
from django.urls import path
from blog import views

from .feeds import LatestPostFeed




app_name ='blog'


urlpatterns = [
   path('',views.Post_list,name='post_list'),
   path('post/',views.Post_list,name='post_list'),
   path('post/create',views.Post_create,name="post_create"),
   path('post/<post_id>',views.Post_detail,name='post_detail'),
   path('post/<post_id>/update',views.Post_update,name="post_update"),
   path('post/<post_id>/delete',views.Post_delete,name='post_delete'),
   path('draft/<post_id>/delete',views.Draft_delete,name='draft_delete'),
   path('draft/<post_id>/publish',views.Draft_publish,name='draft_publish'),
   path('post/approve_comment/<comment_id>',views.approve_comment,name='approve_comment'),
   path('post/remove_comment/<comment_id>',views.disapprove_comment,name='remove_comment'),
   path('sendmail/<post_id>',views.Send_mail,name="send_mail"),
   path('feed/',LatestPostFeed(),name='post_feed'),
   # password change paths
   path('login/',views.UserLogin,name='login'),
   path('logout/',views.UserLogout,name='logout'),
   path('register/',views.UserRegistration,name='register'),
  
  
   
 

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
   'post':PostSitemap
}

urlpatterns = [
    path('',include('portfolio.urls',namespace='portfolio')),
    path('blog/',include('blog.urls',namespace='my_blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/Done',auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

mysite/portfolio/urls.py
from django.urls import path
from . import views
app_name='portfolio'

urlpatterns = [
    path('',views.home,name='home'),
    path('subscribe/',views.subscribe,name='subscribe'),
    path('hire/',views.hire,name='hire')
]

mysite/portfolio/models.py
from django.db import models
from django.core.mail import send_mail

# Create your models here.
class Project(models.Model):
      category=[
        ('Web','Web Develoment'),
        ('Mobile','Mobile Apps')
      ]
      name = models.CharField(max_length=200)
      image = models.ImageField(upload_to='projects/',null=False,blank=False)
      url = models.URLField()
      category = models.CharField(max_length=200,choices=category)


      def __str__(self):
            return self.name

      def save(self,*args,**kwargs):
           subject = 'Emmanuel\'s Portfolio'
           message = 'A new Project with the name @{} has been launched. Please do check it out at {}'.format(self.name,self.url)
           subscribers = Subscriber.objects.all()
           for i in range(len(subscribers)):
                 try:
                   send_mail(subject,message,'obiemmanuel2018@gmail.com',[subscribers[i].email],fail_silently=False)
                 except:
                   print('they was an error sending mail')
           return super().save(*args,**kwargs)
            
                 
              


class Client(models.Model):
      name = models.CharField(max_length=200)
      image = models.ImageField(upload_to='clients/%d/%m/%y',null=False)
      feed_back = models.TextField()

      def __str__(self):
            return str(self.name)
      




class Subscriber(models.Model):
      email = models.EmailField(blank=False,null=False)

      def __str__(self):
            return self.email

class Hire(models.Model):
      company_name=models.CharField(max_length=200,blank=True,null=True)
      email= models.EmailField()
      address = models.CharField(max_length=200)
      contact = models.IntegerField()
      city = models.CharField(max_length=200)
      job = models.CharField(max_length=200)
     


      def __str__(self):
            if self.company_name:
                  return self.company_name
            else:
                  return self.email + ' ' + str(self.address) + ' ' + self.job

mysite/portfolio/forms.py
from django import forms
from .models import Subscriber,Hire


class SubscriberForm(forms.ModelForm):
      class Meta:
            model = Subscriber
            fields=('email',)

class HireForm(forms.ModelForm):
      class Meta:
            model = Hire
            fields=('company_name','email','address','contact','city','job')

mysite/portfolio/views.py
from django.shortcuts import render
from .models import Subscriber,Project,Client
from django.http import JsonResponse
from portfolio.forms import SubscriberForm,HireForm
from django.views.decorators.http import require_POST
# Create your views here.

def home(request):
    projects = Project.objects.all()
    clients = Client.objects.all()
    return render(request,'portfolio/home.html',context={'projects':projects,'clients':clients})
def subscribe(request):
    if request.method=='POST':
       subscribers = Subscriber.objects.all()
       form = SubscriberForm(request.POST);
       if form.is_valid():
          email = request.POST.get('email')
          try:
             form = form.save(commit=False)
             if subscribers:
                 for i in range(len(subscribers)):
                    if email==subscribers[i].email:
                       return JsonResponse({'status':'You are a subscriber'})
             form.email = email
             form.save()
             return JsonResponse({'status':'Ok'})
          except:
              return JsonResponse({'status':'Error'})


@require_POST
def hire(request):
    if request.method =='POST':
       form = HireForm(request.POST)
       if form.is_valid():
          form = form.save(commit=False)
          form.email = request.POST.get('email')
          form.company_name = request.POST.get('company_name')
          form.address = request.POST.get('address')
          form.contact = request.POST.get('contact')
          form.city = request.POST.get('city')
          form.job = request.POST.get('job')

          form.save()
          
          return JsonResponse({'status':'OK'})
       else:
           return JsonResponse({'status':'form is invalid!'})

    else:
       return JsonResponse({'status':'Opps Something went wrong!'})
    
    
    

mysite/portfolio/templates/portfolio/about.html
{% load static %}
<section class="about-area" id='about' >
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-md-12 col-sm-12">
                <div class="about-image">
                    <img src="{% static 'portfolio/images/site-banner.jpg' %}" alt="" class="img-fluid">
                </div>
            </div>
            <div class="col-lg-6 col-md-12 col-sm-12 about-title">
                <h2 class="text-uppercase pt-5">
                    <span>Let me</span>
                    <span>introduce</span>
                    <span>myself</span>
                </h2>
                <div class="paragraph">
                    <p class="para">
                        My name is Emmanuel Obi.
                    </p>
                    <p class="para">
                       I was born 30 June 1999. I attended the presbyterian primary school mutengene where i had my FSLS(First school leaving certificate) in the year 2009. I had my GCE O/A levels at G.B.H.S mutengene at the year 2015 and 2018 respectively.Am currently a level 400 software enginnering student at the faculty of engineering and tectnology at the University Of Buea.
                       

                    </p>

                </div>
                <button type="button" class="btn button-primary text-uppercase">Download Cv</button>
            </div>

        </div>


    </div>

</section>

mysite/portfolio/templates/portfolio/about_me.html
{% load static %}
<section class="about-area">
    <div class="container">
        <div class="row text-center">
            <div class="col-12">
                <div class="about-title">
                    <h1 class="text-uppercase title-h1">
                        Client say about me
                    </h1>
                    <p class="para">
                        CLient say about my work.Legit
                    </p>
                </div>
            </div>
        </div>

    </div>
    <div class="container carousel py-lg-5">
        {% if not clients %}

        <div class="col-12 text-center">
            <p class="title-text text-uppercase">No CLient Yet!</p>
        </div>
        {%else%}
        <div class="owl-carousel owl-theme">
            {%for client in clients %}
            <div class="client row">
                <div class="col-lg-4 col-md-12 client-img">
                    <img src="{{client.image.url}}" alt="" class="img-fluid">
                </div>
                <div class="col-lg-8 col-md-12 about-client">
                    <h4 class="text-uppercase">
                        {{client.name}}
                    </h4>
                    <p class="para">
                        {{client.feed_back}}
                </div>
            </div>
            {%endfor%} {%endif%}

            <div class="owl-dots">

            </div>


        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        $('.site-main .about-area .owl-carousel').owlCarousel({
            loop: true,
            autoplay: true,
            dots: true,
            responsive: {
                0: {
                    items: 1
                },
                544: {
                    items: 2
                }
            }

        })

    })
</script>

mysite/portfolio/templates/portfolio/banner.html
 {% load static %}
<secton class="site-banner" id='home'>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 site-title col-sm-12">
                <h3 class="title-text">Hey

                </h3>
                <img style='width:150px;height:150px;border-radius:50%' src="{% static 'portfolio/images/admin/admin.jpg' %}" alt="admin" class="img-fluid">
                <h1 class="h1 title text-uppercase">I am Obi</h1>
                <h4 class="title text text-uppercase">Full Stack Web developer</h4>
                <div class="site-buttons">
                    <div class="d-flex flex-row flex-wrap">
                        <button type="button" class="btn button-primary mr-4 text-uppercase" id='hire_me'>hire me</button>
                        <button type="button" class="btn button-secondary mr-4 text-uppercase" id='Cv-button'>Get cv</button>
                    </div>
                </div>


            </div>
            <div class="col-lg-8 col-md-12 col-sm-12 ">
                <div class="banner-img">
                    <img src="{% static 'portfolio/images/Mobile-App.png' %}" id='1' class="img-fluid  image"></img>
                    <img src="{% static 'portfolio/images/web.jpg' %}" id='2' class="img-fluid image"></img>
                    <img src="{% static 'portfolio/images/seo.jpg' %}" id='3' class="img-fluid image"></img>


                </div>


                <i style="display: none;" id="prev" class="fas fa-arrow-left" aria-hidden="true"></i>
                <i style="display: none;" id='next' class="fas fa-arrow-right" aria-hidden="true"></i>



            </div>
        </div>
    </div>

</secton>


<script>
    $(document).ready(function() {
        var slideIndex = 0;
        slideShow(0)
        setInterval(function() {
            $('#next').trigger('click')
        }, 5000)
        total_images = $.each($('.image'), function(index, image) {}).length
        $('#prev').click(function() {
            if (slideIndex == 0) {
                slideIndex = total_images
            }
            slideIndex = slideIndex - 1;
            slideShow(slideIndex);

        })
        $('#next').click(function() {
            if (slideIndex == total_images - 1) {
                slideIndex = 0
                slideShow(slideIndex)
            } else {
                slideIndex = slideIndex + 1;
                slideShow(slideIndex);

            }


        })


        function slideShow(n) {
            $.each($('.image'), function(index, image) {
                $('#' + image.id).hide()
            })
            $.each($('.image'), function(index, image) {
                if (index == n) {
                    $('#' + image.id).show(1000)
                }

            })

        }


    })
</script>

mysite/portfolio/templates/portfolio/brand.html
{% load static %}
<section class="brand-area" id='contact'>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-6 col-lg-12 col-md-12 col-sm-12">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/html.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/css.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/js.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/angular.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/ionic.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/python.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-3">
                        <div class="single-brand">
                            <img src="{% static 'portfolio/images/brands/django.jpg' %}" alt="brand-1" class="img-fliud">
                        </div>

                    </div>


                </div>

            </div>
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="experience-area">
                    <div class="d-flex flew-row year-area">
                        <h2 class='p-3 years'>2</h2>
                        <h2>
                            <span>Years</span>
                            <span>Experience</span>
                            <span>Working</span>
                        </h2>
                    </div>
                    <div class="d-flex flex-row flew-wrap call-area">
                        <span><i class="fas fa-phone-alt" aria-hidden="true"></i></span>
                        <div class="call-now">
                            <a href="" class="text-uppercase">Call now</a>
                            <span class="py-2">(+237)-681-14-28-67</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>

mysite/portfolio/templates/portfolio/hire_form.html
<section class="hire-area">

    <div class="container-fluid hire" id='hireform'>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-3 thanks-modal">
                <span id='closeThanks'>&times;</span>
                <p>Thanks for hiring me!</p>
            </div>
        
            <div class="spinner-border m-5" id='spinner' role="status" style='color:whitesmoke;z-index:1;position:absolute;top:40%;right:46%;display:none'>
            <span class="sr-only">Loading...</span>
            </div>
            <div class="col-lg-6 col-md-8 col-sm-12 offset-lg-3 offset md-2 formContainer">
                <span id='closeFormContainer'>&times;</span>
                <form class="hire-form" data-url="{% url 'portfolio:hire' %}" method='POST'>

                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label for="inputEmail4">Email</label>
                        <input type="email" class="form-control" id="inputEmail" name='email'>
                      </div>
                      <div class="form-group col-md-6">
                        <label for="inputPassword4">Companny Name</label>
                        <input type="text" class="form-control" id="inputCompany" name='company_name'>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="inputAddress">Address</label>
                      <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St" name='address'>
                    </div>
                    <div class="form-group">
                        <label for="inputContact">Contact</label>
                        <input type="tel" class="form-control" id="inputContact" name='contact'>
                      </div>
                    
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label for="inputCity">City</label>
                        <input type="text" class="form-control" id="inputCity" name='city'>
                      </div>
                      <div class="form-group col-md-4">
                        <label for="inputState">Job</label>
                        <select id="inputState" class="form-control" name='job'>
                          <option selected>Web development</option>
                          <option >Mobile app development</option>
                          <option >Seo optimization</option>
                        </select>
                      </div>
                     
                    </div>
                    <button id='hire'  type="button" class="btn btn-primary">Hire</button>
                   
                    {% csrf_token %}
                    
                   
                  </form>
                  
                 

            </div>
        </div>


    </div>

</section>


<script>
    $(document).ready(function() {
        $('#hire').click(function(){
                $('.formContainer').hide(500);
                $('#spinner').show(500);

            var serializedData = $('.hire-form').serialize();
            $.ajax({
                url:$('.hire-form').data('url'), 
                data:serializedData,
                type:'post',
                success:function(response){
                    console.log(response.status)
                    if(response.status == 'OK'){
                        $('#spinner').hide(500);
                        $('.thanks-modal').show(500);
                      

                    }
                    
                  
                       
                 
                    
                }

            })
           
        })

        $('#closeThanks').click(function(){
            $('.thanks-modal').hide(500)
            $('#hireform').hide('slow')

        })

        $('#hire_me').click(function() {

            $('#hireform').show(500, function() {
                $('.formContainer').show('slow')
                $('#body').addClass('pause')

            })

        })

        $('#closeFormContainer').click(function() {
            $('.formContainer').hide(500, function() {
                $('#hireform').hide('slow')
                $('#body').removeClass('pause')

            })

        })

    })
</script>

mysite/portfolio/templates/portfolio/home.html
 {% extends 'base.html' %}{{% block content %}
<header class='header_area' style="position: fixed;z-index:1;background:white;width:100%;">
    <!-- navbar area -->
    {% include "portfolio/navbar.html" %}
    <!-- end navbar -->

</header>

<main class='site-main'>
    <!-- hire me area -->
    {% include "portfolio/hire_form.html" %}
    <!-- end hire me area -->
    <!-- Cv area -->
    {% include "portfolio/my_cv.html" %}
    <!-- end Cv area -->
    <!-- banner area -->
    {% include "portfolio/banner.html" %}
    <!-- end banner area -->

    <!-- About area -->
    {% include "portfolio/about.html" %}
    <!-- end about area -->
    <!-- band area -->
    {% include "portfolio/brand.html" %}
    <!-- end band area -->
    <!-- start services area -->
    {% include "portfolio/services.html" %}
    <!-- end services area -->
    <!-- start projects area -->
    {% include "portfolio/projects.html" with projects=projects%}
    <!-- end projects area -->

    <!-- About me -->
    {% include "portfolio/about_me.html" with clients=clients %}
    <!-- end about me -->

    <!-- subscribe -->
    {% include "portfolio/subscribe.html" %}
    <!-- end subscribe area -->

</main>



{% endblock content %}}

mysite/portfolio/templates/portfolio/my_cv.html
{% load static %}
<section class="cv-area">

    <div class="container-fluid Cv" id='Cv'>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 CvContainer">
                <span id='closeCvContainer'>&times;</span>
                  {% comment %} cv goes here {% endcomment %}
                  <img src="{% static 'portfolio/images/cv/Cv.png' %}" alt="cv" >

            </div>
        </div>


    </div>

</section>


<script>
    $(document).ready(function() {
        $('#Cv-button').click(function() {
            $('#Cv').show(500, function() {
                $('.CvContainer').show('slow')
                $('#body').addClass('pause')
            })
        })

        $('#closeCvContainer').click(function() {
            $('.CvContainer').hide(500, function() {
                $('#Cv').hide('slow')
                $('#body').removeClass('pause')

            })

        })

    })
</script>

mysite/portfolio/templates/portfolio/navbar.html
{% load static %}
<div class="main-menu" id='nav'>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">
               Logo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" id='navbarIcon' aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="div mr-auto"></div>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#home">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#about">about</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#services">services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#portfolio">portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#contact">contact</a>
                </li>

            </ul>
        </div>
    </nav>

</div>
<script>
    $(document).ready(function() {
        $('#navbarIcon').click(function() {
            $('#navbarNav').slideToggle(300)

        })


    });
</script>

mysite/portfolio/templates/portfolio/projects.html
{% load static %}
<section class="project-area" id="portfolio">
    <div class="container">
        <div class="project-title pb-5">
            <h1 class="text-uppercase title-h1">
                Recently done projects

            </h1>
            <h1 class="text-uppercase title-h1">
                quality work
            </h1>

        </div>
        <div class="button-groups">
            <button type="button active" data-filter='*'>All</button>
            <button type="button" data-filter=".Web">Web</button>
            <button type="button" data-filter=".Mobile">Mobile</button>
            <button type="button" data-filter=".Seo">Seo</button>
        </div>
        <div class="row grid">
            {% if not projects %}

            <div class="col-12 text-center">
                <h4 class="title-text text-uppercase">No recently Done Porject</h4>
            </div>
            {%else%} {%for project in projects %}
            <div class="col-lg-4 col-md-6 col-sm-12 element-item {{project.category}}">
                <div class="our-project">
                    <div class="img">
                        <a class="test-popup-link" href="{{project.image.url}}">
                            <img src="{{project.image.url}}" alt="" class="img-fluid">
                        </a>

                    </div>
                    <div class="title py-4">
                        <h4 class="text-uppercase">
                            {{project.name}}
                        </h4>
                        <span class="text-secondary">
                            {{project.category}}, porfolio
                        </span><br>
                        <a href="{{project.url}}">
                            <button type="button" class="btn btn-danger">Go Live</button>

                        </a>

                    </div>



                </div>

            </div>
            {%endfor%} {%endif%}


        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        let $btn = $('.project-area .button-groups button');
        $btn.click(function(e) {

            $('.project-area .button-groups button').removeClass('active');
            e.target.classList.add('active')

            let selector = $(e.target).attr('data-filter')
            $('.project-area .grid').isotope({
                filter: selector
            })
            return false;


        })

        $('.project-area .grid .test-popup-link').magnificPopup({
            type: 'image',
            gallery: {
                enabled: true
            }
            // other options
        });



    })
</script>

mysite/portfolio/templates/portfolio/subscribe.html
<section class="subscribe-area">
    <div class="container subscribe">
        <div class="row">
            <div class="col-lg-12 text-center subscribe-title">
                <h4 class="text-uppercase">Get update from anywhere</h4>
                <p class="para">
                    subscribe with email
                </p>
            </div>
        </div>
        <div class="d-sm-flew justify-content-center">
            <form id='form' class="w-50" method='POST' data-url="{% url 'portfolio:subscribe' %}">
                <div class="row d-flex flex-row flex-wrap">
                    <div class="col input-textbox">
                        <input type="text" id='txtemail' class="form-control" placeholder="Email" name='email'>
                    </div>
                    <div class="col">
                        <div class="btn-submit">
                            <button id='subscribe' type="button" class="btn btn-success float-right">Subscribe</button>
                        </div>
                    </div>
                </div>
                <div id='subscribe-success' style="justify-content: center;margin-top:3%;display:none">
                     <p style="color:aqua;font:normal 500 15px/15px 'roboto'">Thanks for subscribing..</p>
                   
                </div>
            
                {% csrf_token %}
            </form>

        </div>

    </div>
</section>
<script>
    $(document).ready(function() {
        $('#subscribe').click(function() {
            $('#subscribe-success').show(500)
            var serializeData = $('#form').serialize();
            console.log(serializeData)
            var email = $('#txtemail').val()
            $.ajax({
                url: $('#form').data('url'),
                data: serializeData,
                email,
                type: 'post',
                success: function(response) {
                    console.log(response)
                }
            })
           
            $('#form')[0].reset();
        })
    })
</script>