mysite/blog/urls.py
from django.urls import path
from blog import views

from .feeds import LatestPostFeed




app_name ='blog'


urlpatterns = [
   path('',views.Post_list,name='post_list'),
   path('post/',views.Post_list,name='post_list'),
   path('post/create',views.Post_create,name="post_create"),
   path('post/<post_id>',views.Post_detail,name='post_detail'),
   path('post/<post_id>/update',views.Post_update,name="post_update"),
   path('post/<post_id>/delete',views.Post_delete,name='post_delete'),
   path('draft/<post_id>/delete',views.Draft_delete,name='draft_delete'),
   path('draft/<post_id>/publish',views.Draft_publish,name='draft_publish'),
   path('post/approve_comment/<comment_id>',views.approve_comment,name='approve_comment'),
   path('post/remove_comment/<comment_id>',views.disapprove_comment,name='remove_comment'),
   path('sendmail/<post_id>',views.Send_mail,name="send_mail"),
   path('feed/',LatestPostFeed(),name='post_feed'),
   # password change paths
   path('login/',views.UserLogin,name='login'),
   path('logout/',views.UserLogout,name='logout'),
   path('register/',views.UserRegistration,name='register'),
  
  
   
 

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
   'post':PostSitemap
}

urlpatterns = [
    path('',include('portfolio.urls',namespace='portfolio')),
    path('blog/',include('blog.urls',namespace='my_blog')),
    path('admin/', admin.site.urls),
    path('sitemap.xml',sitemap,{'sitemaps':sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/Done',auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete')
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

mysite/portfolio/urls.py
from django.urls import path
from . import views
app_name='portfolio'

urlpatterns = [
    path('',views.home,name='home'),
    path('subscribe/',views.subscribe,name='subscribe'),
    path('hire/',views.hire,name='hire')
]

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse




class Post(models.Model):
      STATUS_CHOICE = (
        ('draft','Draft'),
        ('published','Published')
      )

      author = models.ForeignKey(User,on_delete=models.CASCADE,blank=True)
      title = models.CharField(max_length=100)
      body = models.TextField()
      published_date = models.DateTimeField(blank=True,null=True)
      created_date =  models.DateTimeField(default=timezone.now)
      updated_date = models.DateTimeField(blank=True,null=True)
      status = models.CharField(max_length = 10,choices=STATUS_CHOICE,default='draft')
      number_of_views = models.PositiveIntegerField(default=0)
      image = models.ImageField(upload_to='post_images',null=False,blank=False,default='post_images/default_post.jpg')
      views = models.ManyToManyField(User,related_name='views',blank=True)
   

      def approved_comments(self):
          return self.comments.filter(approved_comment = True).order_by('created_date')

      def has_been_viewed(self):
          self.number_of_views = self.number_of_views + 1;
      def publish(self):
          self.published_date = timezone.now()
          self.status='published'
          self.save()

     
      def get_absolute_url(self):
          return reverse('blog:post_detail',args=[self.id])
      def __str__(self):
          return self.title



class UserProfileInfo(models.Model):
      user = models.OneToOneField(User,on_delete=models.CASCADE)
      profile_pic = models.ImageField(upload_to='profile_pics',blank=True,default='profile_pics/default_profile.jpg')
      


class Comment(models.Model):
      
      post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
      author = models.CharField(max_length=200,blank=True)
      author_profile_pic = models.ImageField(null=True,default='profile_pics/default_profile.jpg')
      body = models.TextField(max_length=100)
      created_date = models.DateTimeField(default=timezone.now)
      approved_comment = models.BooleanField(default=False)
      
    



      def approve(self):
          self.approved_comment = True
          self.save()
      
      
      def __str__(self):
          return self.body
        
     

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post,Comment,UserProfileInfo
from blog.forms import PostForm,PostUpdateForm,CommentForm,UserForm,ProfileForm,MailForm
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.decorators.http  import require_POST
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.contrib import messages

from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.forms.models import model_to_dict
from django.core.mail import send_mail
from django.db.models import Count
import pickle
import os
import re
import json 


def get_next_url(next):
    # check if url has next...then get the next page to navigate too after login
    if next:
       next = next.split('/')
       if 'blog:post_detail' in next:
           return next
       elif 'password_change' in next:
             return next
    else:
        return None 



def UserRegistration(request):
    # check if url has next...then get the next page to navigate too after login
    if 'next' in request.GET:
           next=request.GET.get('next')
           navigate_to = get_next_url(next)

           #############################################
    else:
        navigate_to=None

    if request.method=="POST":
        userform = UserForm(request.POST)
        profileform = ProfileForm(request.POST)
   
        if userform.is_valid() and profileform.is_valid():
           user = userform.save()
           user.set_password(user.password)
           user.save()
           profile = profileform.save(commit=False)
           profile.user = user

           if 'profile_pic' in request.FILES:
               profile.profile_pic = request.FILES['profile_pic']
           profile.save()
           user = authenticate(username=userform.cleaned_data['username'],password=userform.cleaned_data['password'])
           login(request,user)
           print(navigate_to)
           if navigate_to:
                   if 'blog:post_detail' in navigate_to:
                       return HttpResponseRedirect(reverse('blog:post_detail',args=[navigate_to[1]]))
                   elif 'password_change' in navigate_to:
                        return HttpResponseRedirect(reverse('password_change'))
           else:
                return HttpResponseRedirect(reverse('blog:post_list'))
           
    else:
        userform = UserForm()
        profileform = ProfileForm()
    return render(request,'registration/register.html',{'userform':userform,'profileform':profileform})

    

def UserLogin(request):

    
    if 'next' in request.GET:
           next=request.GET.get('next')
           navigate_to = get_next_url(next)

    else:
        navigate_to = None

    
    ##################################
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                # if u have a url then navigate to post details page else to post list page
                if navigate_to:
                   if 'blog:post_detail' in navigate_to:
                       return HttpResponseRedirect(reverse('blog:post_detail',args=[navigate_to[1]]))
                   elif 'password_change' in navigate_to:
                        return HttpResponseRedirect(reverse('password_change'))
                   
                else:
                    return HttpResponseRedirect(reverse('blog:post_list'))
            else:
                return HttpResponse('User is in active')
        else: 
            return render(request,'registration/login.html',{'Error':'Invalid Credintials'})

    else:
        return render(request,'registration/login.html')


@login_required
def UserLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:login'))


def Post_list(request):
    if request.POST.get('query'):
       query =  request.POST.get('query')
       searched_post = Post.objects.filter(title__contains=query)[:10]
       context1={}
       clean = re.compile('<.*?>')
       for post in searched_post:
           i = 0
           post.title = re.sub(clean,'',post.title)
           context1[i] = [post.title,post.id] 
           i = i + 1 
       return JsonResponse(context1) 
       
    all_posts = Post.objects.filter(status='published').order_by('-published_date')
    trending_posts = Post.objects.all().annotate(num_comments=Count('comments')).order_by('-num_comments')[:20]
    
    # pagination for all_post
    paginator = Paginator(all_posts, 4) # 3 posts in each page
    page = request.GET.get('page')
    try:
        all_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        all_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        all_posts = paginator.page(paginator.num_pages)

    drafts = Post.objects.filter(status='draft').order_by('-created_date')
    return render(request,'blog/posts/post_list.html',{'all_posts':all_posts,'trending_posts':trending_posts,'drafts':drafts,'page':page})



def Post_detail(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.user.is_anonymous:
        print('Anonymous User')
    else:
        post.views.add(request.user)
   
    ########################################
    # Adding views to post##################
    ########################################
   
    #########################################
    if(request.method == 'POST'):
        user_id = request.POST.get('number')
        user=get_object_or_404(User,id=user_id)
        user_profile_obj = UserProfileInfo.objects.filter(user=user_id)[0]
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.post = post
            comment_form.author = user.username    
            
            if user_profile_obj:
                comment_form.author_profile_pic=user_profile_obj.profile_pic
               
            else:
                 comment_form.author_profile_pic='profile_pics/default_profile.jpg'
            
               
            comment_form.save()
            if not request.user.is_superuser:
               url = request.build_absolute_uri(post.get_absolute_url())
               subject='From Blog:'
               message='Hello Sir, {} just added a comment on {}.follow link to delete or approve comment {}.'.format(request.user,post.title,url)
               send_mail(subject,message,request.user.email,['obiemmanuel2018@gmail.com'],fail_silently=False)
               messages.info(request,'Thanks {} for commenting. Your comment needs to be approved by admin before added to post'.format(user.username))
            return JsonResponse({'comment':{'id':comment_form.id,'author':comment_form.author,'body':comment_form.body,'author_profile_pic':str(comment_form.author_profile_pic),'created_date':comment_form.created_date}})
        else:
            print('Invalid form')
    else:
        comment_form = CommentForm()
    return render(request,'blog/posts/post_detail.html',{'post':post,'comment_form':comment_form})

@login_required
def Post_delete(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    post.delete()
    return HttpResponseRedirect(reverse_lazy('blog:post_list'))



@login_required
def Post_create(request):
    if request.method =='POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            
            form = form.save(commit=False)
            user = get_object_or_404(User,username=request.user)
            form.author=user
            print(user)
            form.status = 'draft'
            form.save()
            return HttpResponseRedirect(reverse('blog:post_list'))
        else:
            print('Form is Invalid')
    else:
        form = PostForm()
    return render(request,'blog/posts/post_create.html',{'form':form})

@login_required
def Post_update(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.method =='POST':
        form = PostUpdateForm(request.POST)
        if form.is_valid():

            cd = form.cleaned_data
            if not  cd['title']:
                post.title = post.title
            else:
                post.title = cd['title']
            if not cd['body']:
                post.body = post.body
            else:
                post.body = cd['body']

            post.save()
            return HttpResponseRedirect(reverse('blog:post_detail',args=[post_id]))
        else:
            print('Form is Invalid')
    else:
        form = PostUpdateForm(initial={'title':post.title,'body':post.body})
    return render(request,'blog/posts/post_update.html',{'form':form,'post':post})





@login_required
def Draft_publish(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    post.publish()
    drafts=Post.objects.filter(status='draft')
    total_drafts = drafts.count()
    return JsonResponse({'status':'OK','total_drafts':total_drafts})

@login_required
def Draft_delete(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    
    post.delete()
    drafts=Post.objects.filter(status='draft')
    total_drafts = drafts.count()
    return JsonResponse({'status':'OK','total_drafts':total_drafts})







################################################################################
################################################################################


@login_required
def approve_comment(request,comment_id):

mysite/blog/templates/blog/posts/all_posts.html
 {% load static %} {% load blog_tags %}
<div class="row" id="all">
    
        <div style="position:absolute;right:0;top:0;background:white;" class="nav flex-column nav-pills mobile" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="javascript:void(0)" role="tab" aria-controls="v-pills-home" aria-selected="true" onclick="is_active('all post')">All</a>
            {% if user.is_superuser%}
             <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="javascript:void(0)" role="tab" aria-controls="v-pills-home" aria-selected="true" onclick="is_active('draft')">Draft <i class='fas fa-envelope-open-text' ></i></a>
            <!--  -->
            {% endif %}

        </div>
    <div class="col-12">
        <h1 style="font-family:'Great Vibes', cursive;margin-left:2%">All post:</h1>
    </div>
    {% if not all_posts %}
    <div class="col-12">
        No post Published yet
    </div>
    {%else%} {% for post in posts %}

    <div class="card col-lg-4 col-md-6 col-lg-4 card-col" style="width: 18rem;" sty>
        <img class="card-img-top" src="{{post.image.url}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{post.title|safe}}</h5>
            <p class="card-text">{{post.body|safe|truncatewords:5}}</p>
            <p style="color: grey;font-size:12px">Published {{post.published_date}} by <a href=""><b style="font-size: 15px;text-transform: capitalize;">{{post.author|truncatewords:3|linebreaksbr}}</b></a></p>

            <span>{{post.approved_comments.count}} <i class="fas fa-envelope"></i> </span>
            <span>{{post.views.count}} <i class="fas fa-eye"></i> </span>
            
            

            <a href="{% url 'blog:post_detail' post_id=post.id %}" style="position: absolute;right:2%;bottom:1%;z-index:2"><button  type="button" class="btn btn-outline-danger">Detail</button></a>
        </div>
    </div>
    {% endfor%}

    <div class="col-12">
        {% include "blog/pagination.html" with page=posts %}
    </div>
    {% endif %}
    <div class="col-12 mobile">
        <div class="col-12" style="background:whitesmoke;padding:20px 20px;border:1px solid whitesmoke;width:100%;height:auto;z-index:1;box-shadow:2px 2px 10px black;margin-top:20px;margin-left:6px">
            <p>Latest Posts:</p>
            {% show_latest_posts 3 %}

        </div>

        <div class="col-12" style="background:whitesmoke;padding:20px 20px;border:1px solid whitesmoke;width:100%;height:auto;z-index:1;box-shadow:2px 2px 10px black;margin-top:20px;margin-left:6px">
            <p>Most Commented Posts:</p>
            {% get_most_commented_posts 3 %}

        </div>

    </div>
</div>


<div class="search-modal" id='searchresult'>
    <span id="closeSearch" style="position: absolute;right:2%;top:2%;font-size:30px;color:whitesmoke;cursor:pointer">&times;</span>
    
    <h5 style="color: whitesmoke;margin-left:-3%">Search Results:</h5>

</div>

mysite/blog/templates/blog/posts/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blog</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <!-- mystyle sheet -->
    <link rel="stylesheet" href="{% static 'blog/css/mystyle.css' %}">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Montserrat&family=Raleway&family=Roboto&display=swap" rel="stylesheet">
    <!-- medius-editor -->
    <link rel="stylesheet" href="{% static 'blog/css/medium-editor.min.css' %}">
    <script src="{% static 'blog/js/medium-editor.min.js' %}"></script>
    <!-- my javascript codes -->
    <script src="{% static 'blog/js/myCodes.js' %}"></script>
    <script src="{% static 'blog/js/Jquery_production.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

    <!-- fontawesome icons -->
    <link href="{% static 'blog/css/fontawesome/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'nlog/css/fontawesome/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/fontawesome/css/solid.css' %}" rel="stylesheet">
    <script>
        var csrftoken = Cookies.get('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>



</head>

<body onscroll="scrolling()" onload="scrollDown()">


    <!-- 
     -->

    <div class="row blogNav">
        <div class="col-12">
            {% if not post %}
            <ul class="nav-container nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'portfolio:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_create' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item" style="background-color: black;">
                    <a class="nav-link" href="{% url 'blog:logout' %}">Logout<i class='fas fa-door-open'></i></a>
                </li>
                {% else %}
                <li class="nav-item" style="background-color: black;">
                    <a class="nav-link" href="{% url 'blog:login' %}">Login<i class='fas fa-door-closed'></i></a>
                </li>
                {% endif %}


            </ul>
            {%endif%}
            <!-- blog div -->
            {% if not post.id %}
            <div class="blog">
                <h2>BLOG</h2>
                <a style="font:normal 500 20px/15px 'roboto'" href="{% url 'password_change' %}">Change password</a>


            <div class="search">
                <form class="form-inline" method='POST' id="searchform">
                   
                    <div class="form-group mx-sm-3 mb-2">
                      <input type="text" class="form-control" id="searchInput" placeholder="search..">
                    </div>
                    <button id='search' type="button" class="btn btn-primary mb-2">Search</button>
                  </form>
                 
            </div>
            </div>
            {% else %}
            <div class="blog-author row">
                <!-- <div class="row Oimage" id="icons">
                    <div class="col-12">
                        <img class="logo" src="icons/icons8-whatsapp-480.png" alt="" onmouseover="changeColor('whatsapp')" onmouseout="changeColor('')">

                    </div>
                    <div class="col-12">
                        <img class="logo" src="icons/icons8-instagram-96.png" alt="" onmouseover="changeColor('instagram')" onmouseout="changeColor('')">

                    </div>
                    <div class="col-12">
                        <img class="logo" src="icons/icons8-facebook-circled-96.png" alt="" onmouseover="changeColor('facebook')" onmouseout="changeColor('')">
                    </div>



                </div> -->
                <div class="col-lg-1 col-sm-1 col-md-1">

                    <div style="margin-top: 0px;margin-left:5%" class="back-btn">
                        <a href="{% url 'blog:post_list' %}"><button  type="button" class="btn btn-outline-danger"><i class="fa fa-arrow-left" aria-hidden="true"></i>
                                Back</button></a>

                    </div>


                    <div style="margin-top:40px" class="share-logos" id="icons">
                        <p>share:</p>
                        <div class="logo">
                            <a href="{% url 'blog:send_mail' post_id=post.id %}"><img class="logo" style="width: 40px;" src="{%static 'blog/images/logos/gmail.svg' %}" alt="" onmouseover="changeColor('gmail')" onmouseout="changeColor('')"></a>
                        </div>


                    </div>
                </div>
                <div class="col-lg-5 col-sm-11 col-md-11 ">


                    <img class='blog-image' style="width: 400px;border-radius:5px;box-shadow:2px 2px 10px black" src={{post.image.url}} alt=" ">
                </div>
                <div class="col-lg-6 col-sm=12 col-md-12 blog-col ">
                    <h2>BLOG</h2>
                    <h4><span>&#9880;</span>{{request.user}}<span>&#9880;</span></h4>
                </div>



            </div>
            {% endif %}
        </div>
    </div>

    {% block content %} {% endblock %}






</body>

<script>
    function is_active(elem) {
        if (elem == 'draft') {
            document.getElementById('draft').style.display = 'flex'

        } else {
            document.getElementById('draft').style.display = 'none'
        }

        if (elem == 'all post') {
            document.getElementById('all').style.display = 'flex'
        } else {
            document.getElementById('all').style.display = 'none'
        }


    }


    $(document).ready(function(){

        $('#search').click(function(){
            $('#search').prop('disabled',true);

            var csrftoken = $('#searchform').serialize();
            var search_val = $('#searchInput').val();
            if(search_val ){
                $.ajax({
                    url:"{%url 'blog:post_list' %}",
                    data:{
                        csrfmiddlewaretoken:csrftoken,
                        query:search_val
    
                    },
                    type:'post',
                    success:function(response){
                       
                        
                           if(response[0]){
                            for(i in response){ 
                                console.log(response)
                                $('#searchresult').append('<a href="'+ response[i][1] +'"><p> ' +response[i][0]+ '</p></a>')
                            }
    
                           }
                           else{
                            $('#searchresult').append('<h4 style="color:whitesmoke">No post found</h4>')
                               
                           }
                          
                           $('#searchresult').slideDown()
                        
                     
                      
                        
                    }
                });

            }
        });
        
        $('#closeSearch').click(function(){
            $('#searchresult').slideUp();
            $('#search').prop('disabled',false);

        })
       
      
    })
</script>

</html>

mysite/blog/templates/blog/posts/draft_list.html
{% load static %}
<div class="row" id="draft">
    <div style="position:absolute;right:0;top:0;background:white;" class="nav flex-column nav-pills mobile" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="javascript:void(0)" role="tab" aria-controls="v-pills-home" aria-selected="true" onclick="is_active('all post')">All</a> {% if user.is_superuser%}
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="javascript:void(0)" role="tab" aria-controls="v-pills-home" aria-selected="true" onclick="is_active('draft')">Draft <i class='fas fa-envelope-open-text' ></i></a>
        <!--  -->
        {% endif %}

    </div>
    <div class="col-12">
        <h1 style="font-family:'Great Vibes', cursive;margin-left:2%">All drafts:</h1>
    </div>

    {% if not drafts %}
    <div class="col-6 offset-3" style="text-align: center;">
        <h3 style="margin-top: 5%;font-family:'Great Vibes';">Draft list is empty</h3>
    </div>

    {% else %} {% for draft in drafts %}


    <div class="card col-lg-4 col-md-6 col-lg-4 card-col" id='card{{draft.id}}' style="width: 18rem;">
        <img class="card-img-top" src="{{draft.image.url}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{draft.title|safe}}</h5>
            <p class="card-text">{{draft.body|safe|truncatewords:5}}</p>
            <p style="color: grey;font-size:12px">created {{draft.created_date}} by <a href=""><b style="font-size: 15px;text-transform: capitalize;">{{post.author|truncatewords:3|linebreaksbr}}</b></a></p>

            <a id='Delete{{draft.id}}' href='javascript:void(0)' data-url="{% url 'blog:draft_delete' post_id=draft.id %}" class="btn btn-danger Delete">Delete</a>
            <a id='Publish{{draft.id}}' href='javascript:void(0)' data-url="{% url 'blog:draft_publish' post_id=draft.id %}" class="btn btn-primary Publish">Publish</a>




        </div>
    </div>

    {%endfor%} {%endif%}

</div>

<script>
    $(document).ready(function() {
        $('.card .Delete').click(function() {

            $.ajax({
                url: $('#' + this.id).data('url'),
                type: 'get',
                success: function(response) {
                    console.log(response)
                    if (response.status == 'OK') {
                        if (response.total_drafts == 0) {
                            $('#draft').append('<div class="col-6 offset-3" style="text-align: center;"><h1 style = "margin-top: 5%;font-family:"Great Vibes";" > Draft list is empty </h1></div>')
                        }


                    }

                }
            })

            $(this).parents('.card').hide(300);




        })

        $('.card .Publish').click(function() {
            $.ajax({
                url: $('#' + this.id).data('url'),
                type: 'get',
                success: function(response) {
                    console.log(response)
                    if (response.status == 'OK') {
                        if (response.total_drafts == 0) {
                            $('#draft').append('<div class="col-6 offset-3" style="text-align: center;"><h1 style = "margin-top: 5%;font-family:"Great Vibes";" > Draft list is empty </h1></div>')
                        }


                    }

                }
            })
            $(this).parents('.card').hide(300);

        })

    });
</script>

mysite/blog/templates/blog/posts/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title|safe|linebreaks|truncatewords:10 }}</a>
    </li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/posts/most_commented_posts.html
<ul>
    {% for post in most_commented_posts %}
    <li>
        <a href="{{post.get_absolute_url}}">{{post.title|safe|linebreaks|truncatewords:10}}</a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/posts/post_create.html
{% extends 'blog/posts/base.html' %} {% load static %}{% block content%}
<div class=" row " style="margin-top: 2%;">
    <div class="col-4 side-image" style="border-right:2px solid whitesmoke;height:450px;overflow:hidden">
        <!-- background icon image -->
        <img src="{% static 'images/background icons/flower.jpg'%}" alt="">


    </div>
    <div class="col-lg-4 col-sm-12 col-md-12 " style="padding: 30px 50px;border-right:2px solid whitesmoke;height:450px;">
        {% if user.is_superuser %}
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %} {{form.as_p}}
            <button type="submit" class="btn btn-danger">create post</button>
        </form>
        {% else %}
        <p>Only the Admin can create a post </p>
        {% endif %}

    </div>
    <div class="col-4 side-image" style="height:450px; overflow:hidden">
        <!-- background icon image -->
        <img src="{% static 'images/background icons/infographics.jpg' %}" alt="">

    </div>
</div>

<script>
    var editor = new MediumEditor('.editable');
    $(document).ready(function(){
        $('#id_author').value='Emmanuel'

    });
</script>



{% endblock %}